title: Peng Andy
description: Peng Andy's website
url: 'https://pengandy.com'
permalink: '/:year-:month-:day-:title/'
# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _scss
  style: compressed
plugins:
  - jekyll-minifier
  - jekyll-redirect-from
  - jekyll-compose
